# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master-taskmaster:
  stage: build
  script:
    - docker build --pull -f containers/taskmaster.Dockerfile -t "$CI_REGISTRY_IMAGE/taskmaster" .
    - docker push "$CI_REGISTRY_IMAGE/taskmaster"
  only:
    - develop-pmnet


build-taskmaster:
  stage: build
  script:
    - docker build --pull -f containers/taskmaster.Dockerfile -t "$CI_REGISTRY_IMAGE/taskmaster:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/taskmaster:$CI_COMMIT_REF_SLUG"
  except:
    - develop-pmnet

build-master-filer:
  stage: build
  script:
    - docker build --pull -f containers/filer.Dockerfile -t "$CI_REGISTRY_IMAGE/filer" .
    - docker push "$CI_REGISTRY_IMAGE/filer"
  only:
    - develop-pmnet

build-filer:
  stage: build
  script:
    - docker build --pull -f containers/filer.Dockerfile -t "$CI_REGISTRY_IMAGE/filer:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/filer:$CI_COMMIT_REF_SLUG"
  except:
    - develop-pmnet
