[tox]
envlist =
  py{310,311,312}-unit,
  py{310,311,312}-lint
skip_missing_interpreters = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
passenv = CI, TRAVIS, TRAVIS_*
deps =
  py{310,311,312}: .[test]
  py{310,311,312}-unit: pytest-cov
    codecov
  py{310,311,312}-lint: pylint
commands =
  py{310,311,312}-unit: pytest -v --cov-report xml --cov tesk_core {posargs} tests
  py{310,311,312}-unit: codecov
  py{310,311,312}-lint: python -m pylint --exit-zero -d missing-docstring,line-too-long,C tesk_core
  py{310,311,312}-lint: python -m pylint -E tesk_core